"""Fleet ground-truth test: every canonical field declared in parser.yaml
is populated on every locked channel in modem.expected.json.

Closes the regression-blindness loop documented in #86. ``modem.expected.json``
is generated by running the parser against ``modem.har`` — if the parser
silently drops a field, both files agree on the gap and ``test_modem_har_replay``
passes despite the gap.

The test is parser.yaml-driven rather than blanket-required: for each
modem, we walk parser.yaml to find which canonical fields it maps for
which channel_types, then assert every locked channel of those types
in modem.expected.json carries those fields. Firmware-gap modems
(where the firmware genuinely doesn't expose a field, so parser.yaml
correctly omits the mapping) pass without false alarms.

Currently checks: ``frequency``. Extend ``_CANONICAL_FIELDS`` as more
silent-drop classes are identified.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
import yaml

# Canonical channel fields whose absence on a channel that *should* have
# them (per parser.yaml) signals a silent parser drop. Keep tight — adding
# a field here adds fleet-wide assertions.
_CANONICAL_FIELDS: frozenset[str] = frozenset({"frequency"})

# Mapping list keys vary by parser format: json uses ``fields``,
# javascript_json/HNAP/etc use ``mappings``, HTML table uses ``columns``.
_MAPPING_LIST_KEYS: tuple[str, ...] = ("fields", "mappings", "columns")


def _modem_dirs() -> list[Path]:
    """Catalog modem directories — parents of test_data/."""
    catalog = Path(__file__).parent.parent / "solentlabs" / "cable_modem_monitor_catalog" / "modems"
    return sorted(p.parent.parent for p in catalog.rglob("test_data/modem.expected.json"))


def _modem_id(modem_dir: Path) -> str:
    return f"{modem_dir.parent.name}/{modem_dir.name}"


def _resolve_channel_types(array: dict[str, Any]) -> set[str]:
    """Determine which channel_types an array section produces.

    Sources, in order:
    1. ``channel_type.fixed`` — single literal type
    2. ``channel_type.map`` — values of the map enumerate the types
    3. A mapping with ``field: channel_type`` and a ``map:`` (TG3442DE
       pattern: channel_type derived per-row from a source key)
    Returns an empty set when none of the above applies — those arrays
    don't generate assertions for this test (we can't tell which types
    they produce).
    """
    ct_config = array.get("channel_type")
    if isinstance(ct_config, dict):
        if "fixed" in ct_config:
            return {ct_config["fixed"]}
        if "map" in ct_config:
            return set(ct_config["map"].values())

    for key in _MAPPING_LIST_KEYS:
        for entry in array.get(key, []) or []:
            if entry.get("field") == "channel_type" and "map" in entry:
                return set(entry["map"].values())

    return set()


def _extract_canonical_fields(array: dict[str, Any]) -> set[str]:
    """Return the canonical field names this array's mappings produce."""
    fields: set[str] = set()
    for key in _MAPPING_LIST_KEYS:
        for entry in array.get(key, []) or []:
            field = entry.get("field")
            if field in _CANONICAL_FIELDS:
                fields.add(field)
    return fields


def _flatten_arrays(section: dict[str, Any]) -> list[dict[str, Any]]:
    """Yield each array config in a section, flattening multi-array form."""
    if "arrays" in section:
        return list(section["arrays"])
    return [section]


def _required_fields_by_type(
    parser_yaml_path: Path,
) -> dict[tuple[str, str], set[str]]:
    """Walk parser.yaml and return ``{(direction, channel_type): {fields}}``.

    For each (direction, channel_type) pair that appears in parser.yaml,
    record the set of canonical fields the parser is expected to produce.
    A channel_type missing from this map produces no assertions.
    """
    parser_config = yaml.safe_load(parser_yaml_path.read_text(encoding="utf-8"))
    requirements: dict[tuple[str, str], set[str]] = {}
    for direction in ("downstream", "upstream"):
        section = parser_config.get(direction)
        if not isinstance(section, dict):
            continue
        for array in _flatten_arrays(section):
            channel_types = _resolve_channel_types(array)
            mapped = _extract_canonical_fields(array)
            if not (channel_types and mapped):
                continue
            for ct in channel_types:
                requirements.setdefault((direction, ct), set()).update(mapped)
    return requirements


@pytest.mark.parametrize("modem_dir", _modem_dirs(), ids=_modem_id)
def test_canonical_fields_populated_per_parser_yaml(modem_dir: Path) -> None:
    """For each canonical field parser.yaml maps for a channel_type, every
    locked channel of that type in modem.expected.json must carry the field.

    Catches the silent-drop case where the parser produced sparse channel
    output (missing canonical fields) and the resulting expected.json
    happily codifies the gap. If the firmware sends data the catalog says
    we should be extracting and the parser drops it, this test fails —
    even when test_modem_har_replay passes.

    Modems whose firmware genuinely doesn't expose a canonical field
    (and whose parser.yaml correctly omits the mapping) pass: the
    requirement isn't generated.
    """
    expected_path = modem_dir / "test_data" / "modem.expected.json"
    parser_yaml_path = modem_dir / "parser.yaml"
    if not parser_yaml_path.exists():
        pytest.skip(f"no parser.yaml at {parser_yaml_path}")
    if not expected_path.exists():
        pytest.skip(f"no expected.json at {expected_path}")

    expected = json.loads(expected_path.read_text(encoding="utf-8"))
    requirements = _required_fields_by_type(parser_yaml_path)
    modem_label = _modem_id(modem_dir)

    gaps: list[str] = []
    for direction in ("downstream", "upstream"):
        for idx, ch in enumerate(expected.get(direction, [])):
            if ch.get("lock_status") and ch["lock_status"] != "locked":
                continue
            ctype = ch.get("channel_type")
            required = requirements.get((direction, ctype))
            if not required:
                continue
            missing = sorted(required - ch.keys())
            if missing:
                gaps.append(
                    f"{modem_label} {direction}[{idx}] "
                    f"(type={ctype}, ch_id={ch.get('channel_id')!r}): missing {missing}"
                )

    assert not gaps, "Parser silently dropped canonical fields:\n  " + "\n  ".join(gaps)
