#!/usr/bin/env python3
"""Build a self-contained HACS zip for a fork that isn't published to PyPI.

Upstream ships the HA integration (``custom_components/cable_modem_monitor``)
as a HACS ``zip_release`` and pulls the engines from PyPI via the
integration's ``manifest.json`` ``requirements``
(``solentlabs-cable-modem-monitor-core``/``-catalog``). A fork with local-only
engine changes (e.g. added modems, new auth strategies) can't rely on those
PyPI packages, so this script produces a **self-contained** artifact:

1. Stage ``custom_components/cable_modem_monitor`` (minus dev-only ``docs/``,
   ``brand/``, and bytecode).
2. Vendor the ``solentlabs.cable_modem_monitor_core`` and ``...catalog`` source
   trees into ``_vendor/solentlabs/`` (excluding ``test_data/`` fixtures).
3. Inject a tiny ``sys.path`` bootstrap so the vendored packages are importable
   at runtime (a no-op in dev, where the editable/PyPI install is used).
4. Rewrite the staged ``manifest.json`` requirements: drop the two
   ``solentlabs-*`` PyPI packages, add the third-party deps the engines need.

The **repo source is never modified** — all edits happen in a temp staging
copy that becomes the zip. Run with ``--verify`` (default) to prove the
vendored artifact imports and parses a modem in an isolated interpreter.

Usage:
    python scripts/dev/build_hacs_zip.py [--output cable_modem_monitor.zip] [--no-verify]
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
INTEGRATION_DIR = REPO_ROOT / "custom_components" / "cable_modem_monitor"
CORE_PKG = REPO_ROOT / "packages" / "cable_modem_monitor_core" / "solentlabs" / "cable_modem_monitor_core"
CATALOG_PKG = REPO_ROOT / "packages" / "cable_modem_monitor_catalog" / "solentlabs" / "cable_modem_monitor_catalog"

# Third-party runtime deps the vendored engines need (from the packages'
# pyproject.toml). cryptography backs the sjcl/cbn auth strategies used by
# some catalog modems, so it is bundled for a full-catalog integration.
VENDORED_REQUIREMENTS = [
    "beautifulsoup4>=4.12",
    "pyyaml>=6.0.2",
    "defusedxml>=0.7.1",
    "pydantic>=2.0",
    "requests>=2.32.3",
    "cryptography>=44.0",
]

FORK_DOCS = "https://github.com/pope523/cable_modem_monitor"
FORK_ISSUES = "https://github.com/pope523/cable_modem_monitor/issues"

# Excluded from the integration copy and the vendored trees.
_PRUNE_DIRS = {"__pycache__", "docs", "brand", "test_data", ".pytest_cache", ".mypy_cache"}
_PRUNE_SUFFIXES = {".pyc", ".pyo", ".actual.json"}

_BOOTSTRAP = '''"""Make the bundled (vendored) ``solentlabs`` packages importable.

Generated by ``scripts/dev/build_hacs_zip.py`` for the self-contained HACS
build. Appends the bundled ``_vendor`` directory to ``sys.path`` so
``import solentlabs.cable_modem_monitor_core`` resolves to the vendored copy
when the packages are not pip-installed. Appending (not inserting) means a
real pip/editable install still wins if one is present, so this is a safe
no-op in a development checkout.
"""

from __future__ import annotations

import sys
from pathlib import Path

_VENDOR = Path(__file__).parent / "_vendor"
if _VENDOR.is_dir():
    _vendor_path = str(_VENDOR)
    if _vendor_path not in sys.path:
        sys.path.append(_vendor_path)
'''


def _ignore(_dir: str, names: list[str]) -> set[str]:
    """shutil.copytree ignore: prune caches, dev-only dirs, and bytecode."""
    pruned = {n for n in names if n in _PRUNE_DIRS}
    pruned |= {n for n in names if any(n.endswith(sfx) for sfx in _PRUNE_SUFFIXES)}
    return pruned


def _stage(staging: Path) -> None:
    """Assemble the self-contained integration tree under *staging*."""
    shutil.copytree(INTEGRATION_DIR, staging, ignore=_ignore)

    vendor_root = staging / "_vendor" / "solentlabs"
    vendor_root.mkdir(parents=True)
    shutil.copytree(CORE_PKG, vendor_root / "cable_modem_monitor_core", ignore=_ignore)
    shutil.copytree(CATALOG_PKG, vendor_root / "cable_modem_monitor_catalog", ignore=_ignore)

    # Bootstrap module + first-import hook in __init__.py (artifact only).
    (staging / "_bootstrap_vendor.py").write_text(_BOOTSTRAP, encoding="utf-8")
    init_path = staging / "__init__.py"
    lines = init_path.read_text(encoding="utf-8").splitlines(keepends=True)
    hook = "from . import _bootstrap_vendor  # noqa: F401,E402  # sets sys.path for vendored solentlabs\n"
    for i, line in enumerate(lines):
        if line.startswith("from __future__ import"):
            lines.insert(i + 1, "\n" + hook)
            break
    else:  # pragma: no cover - __future__ import is always present here
        lines.insert(0, hook)
    init_path.write_text("".join(lines), encoding="utf-8")

    # Rewrite manifest: self-contained requirements + fork URLs.
    manifest_path = staging / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["requirements"] = VENDORED_REQUIREMENTS
    manifest["documentation"] = FORK_DOCS
    manifest["issue_tracker"] = FORK_ISSUES
    manifest["codeowners"] = ["@pope523"]
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def _zip(staging: Path, output: Path) -> None:
    """Zip the *contents* of staging (HACS expects integration files at zip root)."""
    if output.exists():
        output.unlink()
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(staging.rglob("*")):
            if path.is_file():
                zf.write(path, path.relative_to(staging).as_posix())


def _verify(output: Path) -> bool:
    """Extract the zip and import the vendored engine in an isolated interpreter."""
    with tempfile.TemporaryDirectory() as tmp:
        extract = Path(tmp) / "cable_modem_monitor"
        with zipfile.ZipFile(output) as zf:
            zf.extractall(extract)
        vendor = extract / "_vendor"

        # Prove self-containment: strip the editable engine source dirs from
        # the path and any pre-imported solentlabs modules, then import only
        # from the vendored copy. Third-party deps stay available via the venv.
        check = (
            "import sys\n"
            "sys.path = [p for p in sys.path if 'packages/cable_modem_monitor' not in p]\n"
            "for _m in [m for m in sys.modules if m == 'solentlabs' or m.startswith('solentlabs.')]:\n"
            "    del sys.modules[_m]\n"
            f"sys.path.append({str(vendor)!r})\n"
            "import solentlabs.cable_modem_monitor_catalog as cat\n"
            "assert '_vendor' in cat.__file__, cat.__file__\n"
            "from solentlabs.cable_modem_monitor_core.config_loader import load_modem_config\n"
            "nokia = cat.CATALOG_PATH / 'nokia' / 'bgw320_505' / 'modem.yaml'\n"
            "cfg = load_modem_config(nokia)\n"
            "assert cfg.model == 'BGW320-505', cfg.model\n"
            "assert cfg.actions and cfg.actions.restart, 'restart action missing'\n"
            "print('vendored import OK:', cat.__file__)\n"
        )
        result = subprocess.run([sys.executable, "-c", check], capture_output=True, text=True)
        sys.stdout.write(result.stdout)
        if result.returncode != 0:
            sys.stderr.write(result.stderr)
        return result.returncode == 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a self-contained HACS zip")
    parser.add_argument("--output", default=str(REPO_ROOT / "cable_modem_monitor.zip"))
    parser.add_argument("--no-verify", action="store_true", help="Skip the isolated import check")
    args = parser.parse_args()

    output = Path(args.output).resolve()
    with tempfile.TemporaryDirectory() as tmp:
        staging = Path(tmp) / "cable_modem_monitor"
        _stage(staging)
        _zip(staging, output)

    size_kb = output.stat().st_size / 1024
    print(f"Built {output} ({size_kb:.0f} KiB)")

    if not args.no_verify:
        if not _verify(output):
            print("VERIFY FAILED: vendored artifact did not import cleanly", file=sys.stderr)
            return 1
        print("VERIFY OK: artifact is self-contained")
    return 0


if __name__ == "__main__":
    sys.exit(main())
